# Generated by Django 3.2.10 on 2021-12-13 20:20

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('jobs_per_page', models.IntegerField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='JobPostDetail',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('job_description', wagtail.core.fields.StreamField([('job_description', wagtail.core.blocks.RichTextBlock())])),
            ],
            options={
                'verbose_name': 'JobPostDetail',
                'verbose_name_plural': 'JobPostDetails',
            },
            bases=('wagtailcore.page',),
        ),
    ]
