# Generated by Django 3.2.10 on 2021-12-13 20:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0066_collection_management_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('careers', '0002_auto_20211213_2034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobList',
            new_name='CareerListPage',
        ),
    ]
