# Generated by Django 3.2.10 on 2021-12-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapplications', '0004_uploaddocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploaddocument',
            old_name='applicant_email',
            new_name='email',
        ),
        migrations.AddField(
            model_name='uploaddocument',
            name='full_name',
            field=models.CharField(default='Full Name', max_length=100),
            preserve_default=False,
        ),
    ]
