# Generated by Django 3.2.10 on 2021-12-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapplications', '0006_auto_20211214_1335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadDocument',
            new_name='JobApplication',
        ),
    ]
