# Generated by Django 3.2.10 on 2021-12-15 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_rename_joblist_careerlistpage'),
        ('jobapplications', '0008_jobapplication_application_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='jobpost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.jobpostdetail'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='jobtitle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
