# Generated by Django 3.2.10 on 2021-12-23 16:29

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policypage',
            name='text_content',
            field=wagtail.core.fields.StreamField([('text_content', wagtail.core.blocks.RichTextBlock())]),
        ),
    ]
