# Generated by Django 3.2.10 on 2021-12-23 16:47

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_auto_20211223_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policypage',
            name='text_content',
            field=wagtail.core.fields.StreamField([('text_content', wagtail.core.blocks.StructBlock([('paragraph', wagtail.core.blocks.TextBlock(help_text='Add body text', required=True))]))]),
        ),
    ]
