# Generated by Django 3.2.10 on 2021-12-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_alter_policypage_text_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policypage',
            old_name='text_content',
            new_name='container',
        ),
    ]
