# Generated by Django 3.2.10 on 2021-12-23 17:15

from django.db import migrations
import streams.core_blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_rename_text_content_policypage_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policypage',
            name='container',
            field=wagtail.core.fields.StreamField([('text_content', streams.core_blocks.ParagraphBlocks())]),
        ),
    ]
