# Generated by Django 3.2.9 on 2021-12-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='page_para',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='thank_you_text',
            field=models.TextField(null=True),
        ),
    ]
