# Generated by Django 3.2.9 on 2021-12-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20211207_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfield',
            old_name='page',
            new_name='form_page',
        ),
    ]
