# Generated by Django 3.2.9 on 2021-12-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_page_formfield_form_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfield',
            old_name='form_page',
            new_name='page',
        ),
    ]
