# Generated by Django 3.2.9 on 2021-12-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_rename_form_page_formfield_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactpage',
            old_name='page_para',
            new_name='contact_section_para',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='thank_you_text',
        ),
    ]
