# Generated by Django 3.2.9 on 2021-12-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20211208_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactpage',
            old_name='contact_section_para',
            new_name='contact_form_para',
        ),
    ]
