# Generated by Django 3.2.10 on 2021-12-16 06:51

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_rename_contact_section_para_contactpage_contact_form_para'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('e_mail', models.EmailField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('website_url', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
