# Generated by Django 3.2.10 on 2021-12-16 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_formcontact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormContact',
            new_name='ModelContact',
        ),
    ]
