# Generated by Django 3.2.10 on 2021-12-16 07:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_rename_formcontact_modelcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcontact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
