# Generated by Django 3.2.10 on 2021-12-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20211217_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='banner_header',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='banner_intro_small',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_form_para',
            field=models.TextField(null=True),
        ),
    ]
