# Generated by Django 3.2.10 on 2021-12-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_auto_20211217_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelcontact',
            old_name='website_url',
            new_name='business',
        ),
        migrations.AlterField(
            model_name='modelcontact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
