# Generated by Django 3.2.9 on 2021-12-04 00:05

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('banner_intro_small', models.CharField(max_length=50, null=True)),
                ('banner_header', models.CharField(max_length=50, null=True)),
                ('banner_para', models.TextField(null=True)),
                ('container', wagtail.core.fields.StreamField([('heading_and_paragraph', wagtail.core.blocks.StructBlock([('span_units_once', wagtail.core.blocks.CharBlock(help_text='Add a header text', required=True)), ('span_unit_number', wagtail.core.blocks.CharBlock(help_text='Add a header text', required=True)), ('heading', wagtail.core.blocks.CharBlock(help_text='Add a header text', required=True)), ('paragraph', wagtail.core.blocks.TextBlock(help_text='Add body text', required=True))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
