# Generated by Django 3.2.9 on 2021-12-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_genericservicepage_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericservicepage',
            name='contact_section_heading',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='genericservicepage',
            name='contact_section_para',
            field=models.TextField(null=True),
        ),
    ]
