# Generated by Django 3.2.10 on 2021-12-21 20:24

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20211208_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericservicepage',
            name='container',
            field=wagtail.core.fields.StreamField([('heading_and_paragraph', wagtail.core.blocks.StructBlock([('span_units_once', wagtail.core.blocks.CharBlock(help_text='Add a header text', required=True)), ('span_unit_number', wagtail.core.blocks.CharBlock(help_text='Add a header text', required=True)), ('heading', wagtail.core.blocks.CharBlock(help_text='Add a header text', required=True)), ('paragraph', wagtail.core.blocks.TextBlock(help_text='Add body text', required=True))]))], blank=True, null=True),
        ),
    ]
