# Generated by Django 3.2.9 on 2021-12-06 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_pagearticlecategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleCategory',
            new_name='SnippetArticleCategory',
        ),
        migrations.RenameModel(
            old_name='ArticleCategoryOrderable',
            new_name='SnippetArticleCategoryOrderable',
        ),
        migrations.AlterModelOptions(
            name='snippetarticlecategory',
            options={'verbose_name': 'Snippet Article Category', 'verbose_name_plural': 'Snippet Article Categories'},
        ),
    ]
