# Generated by Django 3.2.9 on 2021-12-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211206_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetails',
            name='short_summary',
            field=models.TextField(max_length=160, null=True),
        ),
    ]
