# Generated by Django 3.2.9 on 2021-12-10 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_articledetails_short_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippetarticlecategoryorderable',
            name='category',
        ),
        migrations.RemoveField(
            model_name='snippetarticlecategoryorderable',
            name='page',
        ),
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': 'Article Category', 'verbose_name_plural': 'Article Categories'},
        ),
        migrations.AddField(
            model_name='articledetails',
            name='article_category',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.RESTRICT, related_name='article_category', to='blog.articlecategory'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SnippetArticleCategory',
        ),
        migrations.DeleteModel(
            name='SnippetArticleCategoryOrderable',
        ),
    ]
