# Generated by Django 3.2.9 on 2021-12-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_articledetails_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticleslist',
            name='articles_per_page',
            field=models.IntegerField(default=50, max_length=3),
            preserve_default=False,
        ),
    ]
