# Generated by Django 3.2.9 on 2021-12-11 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogarticleslist_articles_per_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articledetails',
            name='article_category',
        ),
    ]
