# Generated by Django 3.2.10 on 2021-12-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_articledetails_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticleslist',
            name='articles_per_page',
            field=models.IntegerField(),
        ),
    ]
