# Generated by Django 3.2.10 on 2021-12-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogarticleslist_articles_per_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticleslist',
            name='articles_per_page',
            field=models.IntegerField(max_length=3),
        ),
    ]
