# Generated by Django 3.2.9 on 2021-12-03 16:49

from django.db import migrations, models
import streams.core_blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_banner_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='banner_title',
            new_name='banner_header',
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_intro_small',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('rich_para_block', streams.core_blocks.RichParaBlock())], blank=True, null=True),
        ),
    ]
