# Generated by Django 3.2.9 on 2021-12-03 21:03

from django.db import migrations
import wagtail.core.fields
import wagtail.embeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_video_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='video_content',
            field=wagtail.core.fields.StreamField([('video_block', wagtail.embeds.blocks.EmbedBlock(max_height=400, max_width=800))], blank=True, null=True),
        ),
    ]
