# Generated by Django 3.2.9 on 2021-12-03 22:12

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_homepage_video_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='video_content',
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_link',
            field=wagtail.core.fields.StreamField([('video_link', wagtail.core.blocks.URLBlock(icon='media', label='video'))], blank=True, null=True),
        ),
    ]
