# Generated by Django 3.2.9 on 2021-12-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_genericpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericpage',
            old_name='banner_title',
            new_name='banner_header',
        ),
        migrations.AddField(
            model_name='genericpage',
            name='banner_intro_small',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='genericpage',
            name='banner_para',
            field=models.TextField(null=True),
        ),
    ]
