# Generated by Django 3.2.9 on 2021-12-04 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0015_auto_20211203_2350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenericPage',
        ),
    ]
