# Generated by Django 3.2.9 on 2021-12-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_homepagecarousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecarousel',
            name='carousel_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
