# Generated by Django 3.2.9 on 2021-12-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20211208_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='call_to_action',
            field=models.CharField(default='cta', max_length=40),
            preserve_default=False,
        ),
    ]
