# Generated by Django 3.2.9 on 2021-12-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_homepage_call_to_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='call_to_action',
        ),
    ]
