# Generated by Django 3.2.9 on 2021-12-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_homepage_call_to_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cta_button_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_button_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
