# Generated by Django 3.2.9 on 2021-12-11 11:34

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20211211_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='cta_button_2',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_button_1',
            field=wagtail.core.fields.StreamField([('cta_button_1', wagtail.core.blocks.StructBlock([('button_text', wagtail.core.blocks.CharBlock(default='Learn more', max_length=50, required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(default='', required=False)), ('button_url', wagtail.core.blocks.URLBlock(default='', required=False))]))], blank=True, null=True),
        ),
    ]
