# Generated by Django 3.2.9 on 2021-12-11 11:48

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20211211_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='cta_button_1',
            field=wagtail.core.fields.StreamField([('cta_button_1', wagtail.core.blocks.StructBlock([('button_text', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_url', wagtail.core.blocks.URLBlock(required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_button_2',
            field=wagtail.core.fields.StreamField([('cta_button_2', wagtail.core.blocks.StructBlock([('button_text', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_url', wagtail.core.blocks.URLBlock(required=False))]))], blank=True, null=True),
        ),
    ]
