# Generated by Django 3.2.9 on 2021-12-11 12:42

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20211211_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='cta_button_1',
            field=wagtail.core.fields.StreamField([('button_text', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(form_classname='d-block', required=False)), ('external_url', wagtail.core.blocks.URLBlock(form_classname='d-block', required=False))]),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_button_2',
            field=wagtail.core.fields.StreamField([('button_text', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(form_classname='d-block', required=False)), ('external_url', wagtail.core.blocks.URLBlock(form_classname='d-block', required=False))]),
        ),
    ]
