# Generated by Django 3.2.9 on 2021-12-11 13:00

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20211211_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='cta_button_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cta_button_2',
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_1_page',
            field=wagtail.core.fields.StreamField([('cta_1_page', wagtail.core.blocks.PageChooserBlock(required=False))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_1_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_2_page',
            field=wagtail.core.fields.StreamField([('cta_1_page', wagtail.core.blocks.PageChooserBlock(required=False))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_2_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
