# Generated by Django 3.2.9 on 2021-12-12 18:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20211211_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cta_content',
            field=wagtail.core.fields.StreamField([('cta', wagtail.core.blocks.StructBlock([('button_text', wagtail.core.blocks.CharBlock(default='Learn More', required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False))]))], blank=True, null=True),
        ),
    ]
