# Generated by Django 3.2.9 on 2021-12-12 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0034_homepage_cta_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='firstcta_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='first_cta', to='wagtailcore.page'),
        ),
    ]
