# Generated by Django 3.2.9 on 2021-12-12 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_articledetails_article_category'),
        ('home', '0035_homepage_firstcta_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='cta_content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='first_cta_page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='first_cta_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='firstcta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='second_cta_page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='second_cta_text',
        ),
        migrations.RemoveField(
            model_name='homepagearticles',
            name='article_container',
        ),
        migrations.AddField(
            model_name='homepagearticles',
            name='article_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='homearticle', to='blog.articledetails'),
        ),
    ]
