# Generated by Django 3.2.9 on 2021-12-12 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_articledetails_article_category'),
        ('home', '0036_auto_20211212_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='first_article_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='firstarticle', to='blog.articledetails'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_article_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='secondarticle', to='blog.articledetails'),
        ),
        migrations.DeleteModel(
            name='HomePageArticles',
        ),
    ]
