# Generated by Django 3.2.10 on 2021-12-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20211212_1929'),
        ('home', '0037_auto_20211212_2015'),
    ]

    operations = [
    ]
