# Generated by Django 3.2.10 on 2021-12-31 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_megamenuitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MegaMenuItem',
        ),
    ]
