# Generated by Django 3.2.10 on 2021-12-31 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_megamenu_megamenuitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MegaMenu',
        ),
        migrations.DeleteModel(
            name='MegaMenuItem',
        ),
    ]
