# Generated by Django 3.2.10 on 2021-12-31 14:58

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_megamenu_megamenuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megamenuitem',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='mega_menu_items', to='menus.megamenu'),
        ),
    ]
