# Generated by Django 3.2.10 on 2021-12-31 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_alter_megamenuitem_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='megamenuitem',
            name='parent_link',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='menuchildren', to='menus.menuitem'),
            preserve_default=False,
        ),
    ]
